WebApplication/Models/WeapModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication.Models
{
    public class WeapModels
    {
        public String WeaponName { get; set; }
        public String WeaponType { get; set; }
        public String WeaponMade { get; set; }
        public String WeaponRate { get; set; }
        public String WeaponPrice { get; set; }
        public String PicUrl { get; set; }
    }
}

WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication/Controllers/WeapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class WeapController : Controller
    {
        // GET: Weap
        public ActionResult Weap()
        {
            WeapModels[] weapons = {
                                           new WeapModels{WeaponName ="AK", WeaponMade= "USSR", WeaponPrice = "500", PicUrl="AK.jpg"},
                                           new WeapModels{WeaponName ="M-60", WeaponMade= "USA", WeaponPrice = "1 500", PicUrl="m60.jpg"},
                                           new WeapModels{WeaponName ="RPG", WeaponMade= "USSR", WeaponPrice = "1 000", PicUrl="RPG.jpg"},
                                           new WeapModels{WeaponName ="Light Saber", WeaponMade= "Old Republic", WeaponPrice = "27 999", PicUrl="LightSaber.jpg"},
                                           new WeapModels{WeaponName ="Bolter", WeaponMade= "Imperium", WeaponPrice = "10 000", PicUrl="Bolter.jpg"},

                                       };


            return View(weapons);
        }

        public ActionResult Lottery()
        {
            WeapModels lot = new WeapModels
            {
                WeaponName = "Light Saber",
                WeaponMade = "Old Republic",
                WeaponPrice = "27 999",
                PicUrl = "LightSaber.jpg"
            };

            return View(lot);
        }
    }
}

WebApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<br />
<div class="col-md-12 text-center">
    <img src="~/Content/Images/AK-lg.jpg">
</div>
<br />
<div class="col-md-12 text-center ">
    <h1> Welcome to our Black Market</h1>
</div>
<p class="lead text-info text-center">A black market, underground economy, or shadow economy is a market characterized by some form of noncompliant behavior with an institutional set of rules.</p>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - BM</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Black+Ops+One' rel='stylesheet' type='text/css'>
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Black Market", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">
                    <li><a href="/Weap/Weap">Market</a></li>
                    <li><a href="/Weap/lottery">Lottery</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-muted">&copy;  rights is not reserved</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WebApplication/Views/Weap/Lottery.cshtml
@model WebApplication.Models.WeapModels
@{
    ViewBag.Title = "Lottery";
}




@{

    Random r = new Random();
}

<br />
<p class="lead text-info">
    Не проходите мимо. Только сегодня у вас есть уникальный шанс сбить цену на один из лолов нашего замечательного черного рынка!
</p>
<table class="table table-hover table-striped row">
    <thead>
        <tr>
            <th>LOT</th>
            <th>PRICE</th>
            <th>MADE</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col-md-4">
                <h3> @Model.WeaponName</h3>
            </td>
            <td class="col-md-2">
                <h3 class="text-warning"> $ @(r.Next(10000, 50000))</h3>
            </td>
            <td class="col-md-2">
                <h3>@Model.WeaponMade</h3>
            </td>
        </tr>
    </tbody>
</table>


<div class="thumbnail  col-md-12">
    <img src="~/Content/Images/@Model.PicUrl" alt="@Model.WeaponName" class="img-responsive">
</div>

<br />
<div class=" text-center">
    @Html.ActionLink("CHANGE PRICE", "lottery", "Weap", new { area = "" }, new { @class = "btn btn-success " })


</div>

WebApplication/Views/Weap/Weap.cshtml
@model WebApplication.Models.WeapModels[]
@{
    ViewBag.Title = "Index";
}
<table class="table table-hover table-striped row">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Made</th>
            <th>review</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model)
        {
            <tr>
                <td class="col-md-4">
                    <h3>@c.WeaponName</h3>
                </td>
                <td class="col-md-2">
                    <h3>$ @c.WeaponPrice</h3>
                </td>
                <td class="col-md-2">
                    <h3>@c.WeaponMade</h3>
                </td>
                <td>
                    <div class="thumbnail  col-md-4">
                        <img src="~/Content/Images/@c.PicUrl" alt="@c.WeaponName" class="img-responsive">
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>